### ISSUE TITLE
Dubs

### ISSUE THREAD

**Issue by falsisdev** [lunexdev/TheMechanicsGuard#1]
config.json kullanmak yerine database modülü kullan. Yakında yapıp Pull Request attım

**Comment by lunexdev** [comment]
ha config den çekilmiş ha db den , db den çekmek için eklendiği yer olması lazım.
suncucuya özel olduğundandan ayarlamaya ihtiyaç yok.

**Comment by falsisdev** [comment]
İşte diyorum ya sunucuya özel olmasın da insanlar ayarlasın daha çok tutar. Neyse zaten yarın pr atarım
